'use client'

import { createContext, useContext, useState, useEffect, ReactNode } from 'react'

type Language = 'fr' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Traductions
const translations = {
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.about': 'À propos',
    'nav.experience': 'Expérience',
    'nav.projects': 'Projets',
    'nav.education': 'Formation',
    'nav.contact': 'Contact',
    
    // Hero
    'hero.name': 'Ghada Turki',
    'hero.title': 'Étudiante ingénieure en Électromécanique – 5ᵉ année à ESPRIT',
    'hero.master': 'Titulaire d\'un Master professionnel en Mécatronique',
    'hero.tagline': 'Je transforme les idées en prototypes… et les problèmes industriels en solutions intelligentes',
    'hero.viewProjects': 'Voir mes projets',
    'hero.downloadCV': 'Télécharger mon CV',
    
    // About
    'about.title': 'À propos',
    'about.subtitle': 'Profil Ingénieur',
    'about.professionalProfile': 'Profil professionnel',
    'about.description': 'Titulaire d\'un Master professionnel en Mécatronique et ingénieure en Génie Électromécanique, avec une expertise en conception mécanique, automatisation et développement logiciel. Passionnée par l\'innovation et les systèmes automatisés, je cherche à appliquer mes compétences dans un environnement dynamique à travers un stage de fin d\'études.',
    'about.objective': 'Mon objectif est de contribuer à la transformation digitale de l\'industrie en développant des solutions intelligentes qui combinent mécanique, électronique et intelligence artificielle.',
    'about.keyDomains': 'Domaines clés',
    'about.industrialAutomation': 'Automatisation industrielle',
    'about.industrialAutomationDesc': 'Conception et développement de systèmes automatisés pour l\'industrie 4.0',
    'about.robotics': 'Robotique',
    'about.roboticsDesc': 'Développement de robots autonomes et systèmes robotiques intelligents',
    'about.iot': 'IoT & Systèmes embarqués',
    'about.iotDesc': 'Intégration de capteurs, microcontrôleurs et protocoles de communication',
    'about.ar': 'Réalité augmentée',
    'about.arDesc': 'Applications AR pour la formation et la maintenance industrielle',
    'about.softSkills': 'Soft Skills',
    'about.innovation': 'Innovation',
    'about.teamwork': 'Travail d\'équipe',
    'about.autonomy': 'Autonomie',
    'about.analytical': 'Esprit analytique',
    'about.problemSolving': 'Résolution de problèmes',
    'about.leadership': 'Leadership',
    
    // Experience
    'experience.title': 'Expérience',
    'experience.subtitle': 'Parcours professionnel',
    'experience.matech2025.position': 'Mémoire de fin d\'études',
    'experience.matech2025.description': 'Conception et réalisation d\'un émulateur de groupe électrogène et développement de son application mobile en réalité augmentée',
    'experience.gd2025.position': 'Stage d\'ingénieur',
    'experience.gd2025.description': 'Développement d\'une solution innovante de supervision de la production avec application desktop Python et système de comptage automatisé',
    'experience.matech2023.position': 'Stage de fin d\'études',
    'experience.matech2023.description': 'Conception et réalisation d\'un simulateur de pannes d\'un groupe électrogène avec application mobile Java',
    'experience.csm2022.position': 'Stage de technicien',
    'experience.csm2022.description': 'Amélioration de la machine Trepko Seau - Conception d\'une machine pour la mise en place des récipients sur le tapis',
    'experience.wewire2021.position': 'Stage d\'initiation',
    'experience.wewire2021.description': 'Découverte des activités de l\'entreprise, apprentissage de la fabrication des câbles et application des principes du Lean',
    
    // Projects
    'projects.title': 'Projets',
    'projects.subtitle': 'Découvrez mes réalisations en ingénierie, de la robotique à l\'intelligence artificielle',
    'projects.viewDetails': 'Voir détails',
    'projects.description': 'Description',
    'projects.problem': 'Problématique',
    'projects.solution': 'Solution',
    'projects.technologies': 'Technologies utilisées',
    'projects.close': 'Fermer',
    'projects.project1.title': 'Robot autonome de détection de fissures',
    'projects.project1.description': 'Robot intelligent utilisant l\'IA pour détecter automatiquement les fissures dans les structures',
    'projects.project1.problem': 'Détection manuelle des fissures coûteuse et sujette aux erreurs dans les inspections industrielles',
    'projects.project1.solution': 'Développement d\'un robot autonome équipé de caméras et d\'algorithmes d\'IA pour la détection automatique',
    'projects.project1.detail': 'Robot de détection des fissures réalisé par VGG16, qui est un modèle de réseau de neurones convolutifs profond (CNN) spécialisé dans la classification d\'images. Le système utilise une carte ESP32 pour le contrôle du robot et le traitement en temps réel des images capturées par la caméra. Le modèle VGG16, pré-entraîné sur ImageNet, a été fine-tuné pour détecter et classifier les fissures dans les structures, permettant une inspection automatisée et précise.',
    'projects.project2.title': 'Émulateur de groupe électrogène + AR',
    'projects.project2.description': 'Application mobile en réalité augmentée pour explorer virtuellement les composants d\'un groupe électrogène',
    'projects.project2.problem': 'Formation technique complexe et coûteuse pour les techniciens sur les groupes électrogènes',
    'projects.project2.solution': 'Application AR immersive avec quiz intégré permettant l\'apprentissage interactif des composants',
    'projects.project7.title': 'Simulateur de pannes de groupe électrogène',
    'projects.project7.description': 'Conception et réalisation d\'un simulateur de pannes d\'un groupe électrogène avec application mobile',
    'projects.project7.problem': 'Formation des techniciens sur les pannes de groupes électrogènes nécessite un équipement réel coûteux et complexe',
    'projects.project7.solution': 'Développement d\'un simulateur de pannes avec contrôleur Guardrevolution et application mobile Java pour l\'apprentissage',
    'projects.project3.title': 'Système automatisé de comptage des câbles',
    'projects.project3.description': 'Système automatisé de comptage des câbles en environnement industriel, intégrant une solution électronique, logicielle et mécanique',
    'projects.project3.problem': 'Le comptage manuel des câbles produits est chronophage, sujet aux erreurs humaines et peu fiable pour le suivi en temps réel de la production',
    'projects.project3.solution': 'Développement d\'un poste de comptage automatisé basé sur un capteur de proximité, une carte Arduino et une communication série pour la transmission des données',
    'projects.project3.detail': 'Système automatisé de comptage des câbles en environnement industriel, intégrant une solution électronique, logicielle et mécanique pour améliorer la supervision de la production et la fiabilité des données de fabrication.',
    'projects.project3.features': 'Fonctionnalités principales',
    'projects.project3.feature1': 'Détection automatique du passage des câbles',
    'projects.project3.feature2': 'Comptage fiable et précis en temps réel',
    'projects.project3.feature3': 'Transmission des données vers une application de supervision',
    'projects.project3.feature4': 'Intégration facile dans une ligne de production existante',
    'projects.project3.electronic': 'Conception électronique',
    'projects.project3.electronic1': 'Remplacement de la carte initiale par une carte Arduino',
    'projects.project3.electronic2': 'Intégration d\'un capteur de proximité E3F-DS30C4',
    'projects.project3.electronic3': 'Réalisation du schéma de câblage complet',
    'projects.project3.electronic4': 'Tests de fiabilité en conditions industrielles',
    'projects.project3.programming': 'Programmation',
    'projects.project3.programming1': 'Programmation sous Arduino IDE',
    'projects.project3.programming2': 'Implémentation d\'un algorithme de détection de front descendant pour garantir un comptage précis et éviter les doublons',
    'projects.project3.programming3': 'Incrémentation automatique du compteur',
    'projects.project3.programming4': 'Communication série pour l\'affichage et l\'exploitation des données',
    'projects.project3.mechanical': 'Conception mécanique & Réalisation',
    'projects.project3.mechanical1': 'Conception complète du poste de travail sous SolidWorks',
    'projects.project3.mechanical2': 'Montage complet du système (Arduino + capteur + structure mécanique)',
    'projects.project3.mechanical3': 'Validation du bon fonctionnement du comptage automatique',
    'projects.project8.title': 'Application desktop intelligente de gestion et suivi de production',
    'projects.project8.description': 'Application desktop intelligente dédiée à la gestion et au suivi de la production industrielle, permettant de remplacer un système manuel basé sur des fiches papier par une solution numérique automatisée',
    'projects.project8.problem': 'Le suivi reposait sur des fiches papier remplies manuellement, un comptage physique via des courroies numérotées et un calcul a posteriori. Ce système était chronophage, sujet aux erreurs humaines et peu adapté au suivi en temps réel',
    'projects.project8.solution': 'Développement d\'une application desktop complète intégrant la gestion des ouvriers, le suivi des shifts, la collecte et l\'analyse des données, avec reconnaissance faciale et QR codes',
    'projects.project9.title': 'Application mobile d\'interprétation des codes d\'erreur d\'un groupe électrogène',
    'projects.project9.description': 'Application mobile simple permettant aux techniciens de saisir un code d\'erreur affiché sur le contrôleur Guard Revolution AMF25 et d\'afficher instantanément la description détaillée du défaut',
    'projects.project9.problem': 'Les codes d\'erreur affichés sur le contrôleur sont techniques et peu explicites, difficiles à interpréter sans documentation, source de perte de temps pour les techniciens lors des interventions',
    'projects.project9.solution': 'Développement d\'une application mobile légère et intuitive permettant la saisie manuelle du code d\'erreur et l\'affichage instantané de sa signification détaillée',
    'projects.project4.title': 'Suiveur de ligne & détecteur d\'obstacles',
    'projects.project4.description': 'Robot autonome capable de suivre une ligne et d\'éviter les obstacles de manière intelligente',
    'projects.project4.problem': 'Besoin de robots autonomes pour la navigation dans des environnements structurés',
    'projects.project4.solution': 'Développement d\'un robot avec algorithmes de suivi de ligne et détection d\'obstacles',
    'projects.project5.title': 'Bras robotique dessinant sur bois (Woodcraft)',
    'projects.project5.description': 'Commande précise d\'un bras robotique pour réaliser des motifs complexes sur le bois',
    'projects.project5.problem': 'Réalisation manuelle de motifs complexes sur bois longue et imprécise',
    'projects.project5.solution': 'Programmation d\'un bras robotique avec trajectoires précises pour l\'usinage artistique',
    'projects.project5.objective': 'Objectif du Projet',
    'projects.project5.objectiveDesc': 'Le but de notre projet est de créer un woodcraft, où un robot sera capable d\'écrire un mot ou de dessiner sur du bois de manière artisanale. Dans notre cas, le robot sera chargé d\'écrire le mot "meca" sur une surface en bois.',
    'projects.project5.step1': 'Conception sur SolidWorks',
    'projects.project5.step1Desc': 'La première étape consiste à concevoir la table de travail, l\'emplacement du robot et la pièce sur laquelle il écrira le mot "meca". Cette conception détaillée a été réalisée à l\'aide du logiciel SolidWorks.',
    'projects.project5.step2': 'Programmation avec RT Tool Box - Création du Hand',
    'projects.project5.step2Desc': 'Nous avons utilisé le logiciel RT Tool Box pour programmer le robot. Dans un premier temps, nous avons créé notre hand, définissant ainsi la configuration des outils et des effecteurs que le robot utilisera pour l\'écriture sur bois.',
    'projects.project5.step3': 'Intégration des Pièces à RT Tool Box',
    'projects.project5.step3Desc': 'Suite à la création du hand, nous avons intégré les pièces conçues précédemment sur SolidWorks dans le logiciel RT Tool Box. Cette étape garantit la synchronisation entre les éléments mécaniques et la programmation, assurant une exécution cohérente des mouvements du robot.',
    'projects.project5.step4': 'Programmation Avancée avec la Méthode de Teaching de Robot',
    'projects.project5.step4Desc': 'Enfin, par le biais de la méthode de teaching de robot, nous avons affiné la programmation du robot. Cette approche interactive a permis au robot d\'apprendre et de s\'adapter dynamiquement à la surface du bois, améliorant ainsi sa capacité à écrire le mot "meca" avec précision et efficacité.',
    'projects.project5.highlights': 'Points forts du projet',
    'projects.project5.highlight1': 'Intégration complète : De la conception 3D (SolidWorks) à la programmation robotique (RT Tool Box)',
    'projects.project5.highlight2': 'Précision artisanale : Réalisation de motifs complexes avec une grande précision',
    'projects.project5.highlight3': 'Méthode de teaching : Adaptation dynamique du robot à la surface du bois',
    'projects.project5.highlight4': 'Automatisation : Réduction du temps de production et amélioration de la reproductibilité',
    'projects.project5.highlight5': 'Application industrielle : Solution applicable à la personnalisation de produits en bois',
    'projects.project6.title': 'Réservoir intelligent avec Node-RED',
    'projects.project6.description': 'Système de monitoring intelligent d\'un réservoir avec dashboard temps réel et alertes',
    'projects.project6.problem': 'Surveillance manuelle des réservoirs inefficace et risque de débordement ou de pénurie',
    'projects.project6.solution': 'Dashboard Node-RED avec MQTT et ESP32 pour le monitoring en temps réel et alertes automatiques',
    'projects.project10.title': 'Application de supervision industrielle & indicateurs de maintenance',
    'projects.project10.description': 'Application de supervision industrielle permettant l\'acquisition, l\'enregistrement et l\'analyse des arrêts machine, données de production et paramètres process, avec calcul automatique des indicateurs de maintenance MTTR et MTBF',
    'projects.project10.problem': 'Dans un environnement industriel, l\'absence d\'un système de supervision structuré entraîne une mauvaise traçabilité des arrêts machine, un suivi limité de la production et de la consommation matière, et une difficulté à analyser les performances et la maintenance',
    'projects.project10.solution': 'Développement d\'une application de supervision centralisée intégrant l\'acquisition des signaux d\'arrêt via une carte d\'acquisition, l\'enregistrement des données process dans une base de données, et une interface graphique multi-fenêtres pour le suivi, l\'analyse et la prise de décision',
    'projects.project10.value': 'Valeur ajoutée du projet',
    'projects.project10.value1': 'Vision complète acquisition → supervision → analyse',
    'projects.project10.value2': 'Compétences en maintenance industrielle',
    'projects.project10.value3': 'Exploitation des données pour l\'aide à la décision',
    'projects.project10.value4': 'Intégration WinDev et Proteus 8',
    'projects.project10.detail': 'Application de supervision industrielle permettant l\'acquisition, l\'enregistrement et l\'analyse des arrêts machine, données de production et paramètres process, avec calcul automatique des indicateurs de maintenance MTTR et MTBF, développée sous WinDev.',
    'projects.project10.problematic': 'Problématique',
    'projects.project10.problematicDesc': 'Dans un environnement industriel, l\'absence d\'un système de supervision structuré entraîne :',
    'projects.project10.problematic1': 'une mauvaise traçabilité des arrêts machine',
    'projects.project10.problematic2': 'un suivi limité de la production et de la consommation matière',
    'projects.project10.problematic3': 'une difficulté à analyser les performances et la maintenance',
    'projects.project10.solutionTitle': 'Solution',
    'projects.project10.solutionDesc': 'Développement d\'une application de supervision centralisée intégrant :',
    'projects.project10.solution1': 'l\'acquisition des signaux d\'arrêt via une carte d\'acquisition',
    'projects.project10.solution2': 'l\'enregistrement des données process dans une base de données',
    'projects.project10.solution3': 'une interface graphique multi-fenêtres pour le suivi, l\'analyse et la prise de décision',
    'projects.project10.acquisition': 'Acquisition des arrêts machine',
    'projects.project10.acquisition1': 'Pin 11 : Arrêt défaut alimentation',
    'projects.project10.acquisition2': 'Pin 10 : Arrêt défaut pression',
    'projects.project10.acquisition3': 'Pin 9 : Arrêt opérateur',
    'projects.project10.acquisitionDesc': 'Chaque arrêt est enregistré avec : type d\'arrêt, date et heure, historique consultable',
    'projects.project10.interface': 'Interface graphique (WinDev)',
    'projects.project10.window1': 'Fenêtre 1 – Arrêts & Maintenance',
    'projects.project10.window1Desc': 'Liste des arrêts avec type, date, heure. Filtrage par type et par période. Calcul et affichage des indicateurs : MTTR (Mean Time To Repair) et MTBF (Mean Time Between Failures)',
    'projects.project10.window2': 'Fenêtre 2 – Suivi de la production',
    'projects.project10.window2Desc': 'Affichage de la production journalière : pièces conformes, pièces non conformes, production totale. Analyse rapide de la performance de production',
    'projects.project10.window3': 'Fenêtre 3 – Suivi process',
    'projects.project10.window3Desc': 'Suivi de la consommation de matière première en fonction du temps (par jour). Historique de la température. Détection et enregistrement des dépassements de seuil (température > 70 °C). Filtrage des données par date',
    'projects.project10.windowMain': 'Fenêtre principale',
    'projects.project10.windowMainDesc': 'Menu central permettant l\'accès aux différentes fenêtres. Navigation simple et intuitive',
    'projects.project10.development': 'Développement & Programmation',
    'projects.project10.dev1': 'Programmation de la carte d\'acquisition',
    'projects.project10.dev2': 'Acquisition et enregistrement : des arrêts machine, des données de production, des données de température, de la consommation de matière première',
    'projects.project10.dev3': 'Développement de l\'interface graphique et de la base de données sous WinDev',
    'projects.project10.dev4': 'Implémentation des filtres et calculs statistiques',
    
    // Education
    'education.title': 'Formation',
    'education.subtitle': 'Parcours académique',
    'education.esprit.degree': 'Cycle d\'ingénieur en Électromécanique – Spécialité Mécatronique',
    'education.esprit.institution': 'École Supérieure Privée d\'Ingénierie et de Technologies - ESPRIT',
    'education.esprit.period': '2024 - Présent',
    'education.esprit.status': 'En cours',
    'education.esprit.description': 'Formation approfondie en mécatronique, automatisation et systèmes intelligents',
    'education.istic.degree': 'Mastère Professionnel co-construit en Mécatronique',
    'education.istic.institution': 'Institut Supérieur des Technologies de l\'Information et des Communications - ISTIC',
    'education.istic.period': '2023 - 2025',
    'education.istic.status': 'Diplômé',
    'education.istic.description': 'Spécialisation en systèmes mécatroniques et intégration mécanique-électronique-informatique',
    'education.isetn.degree': 'Licence appliquée en génie mécanique',
    'education.isetn.institution': 'Institut supérieur des études technologiques de Nabeul - ISETN',
    'education.isetn.period': '2020 - 2023',
    'education.isetn.status': 'Diplômé',
    'education.isetn.description': 'Fondations en génie mécanique, conception et fabrication',
    'education.certifications': 'Certifications',
    'education.associative': 'Vie associative',
    'education.associative.member': 'Membre dans l\'association d\'Education Relative à l\'Environnement de Hammamet',
    'education.associative.memberDesc': 'Participation dans plusieurs chantiers et formations.',
    'education.aiesec.title': 'AIESEC – Stage volontaire en Turquie, Izmit (06/2023 - 08/2023)',
    'education.aiesec.description': 'Collaboration internationale pour organiser des événements communautaires, animation de sessions "Talk to Practice" en anglais et direction d\'activités éducatives pour enfants et adultes. Certification obtenue en Leadership Development Experience dans le cadre du projet Global Volunteer "Youth 4 Impact" visant l\'Objectif de Développement Durable #4 (Éducation de qualité).',
    'education.aiesec.download': 'Télécharger le certificat Leadership Development Experience',
    'education.bal.title': 'Bal des Projets 2025 – ESPRIT',
    'education.bal.description': 'Dans le cadre du Bal des Projets 2025 organisé par ESPRIT, j\'ai eu l\'opportunité de collaborer avec une équipe de 6 personnes sur un projet de détection automatique de fissures. Cette expérience m\'a permis de renforcer mes compétences en travail d\'équipe et en résolution de problèmes techniques.',
    'education.bal.download': 'Télécharger l\'attestation de participation',
    'education.download': 'Télécharger',
    
    // Contact
    'contact.title': 'Contact',
    'contact.subtitle': 'Intéressé par mon profil ? N\'hésitez pas à me contacter pour discuter de vos projets',
    'contact.info': 'Informations de contact',
    'contact.infoDesc': 'Je suis disponible pour discuter de projets, stages ou opportunités de collaboration dans le domaine de l\'ingénierie et de l\'innovation technologique.',
    'contact.email': 'Email',
    'contact.phone': 'Téléphone',
    'contact.location': 'Localisation',
    'contact.social': 'Réseaux sociaux',
    'contact.fullName': 'Nom complet',
    'contact.namePlaceholder': 'Votre nom',
    'contact.emailPlaceholder': 'votre.email@example.com',
    'contact.subject': 'Sujet',
    'contact.subjectPlaceholder': 'Sujet de votre message',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Votre message...',
    'contact.send': 'Envoyer le message',
    'contact.sent': 'Message envoyé !',
    
    // Footer
    'footer.tagline': 'Transformer la mécanique en systèmes intelligents',
    'footer.quickLinks': 'Liens rapides',
    'footer.about': 'À propos',
    'footer.projects': 'Projets',
    'footer.contact': 'Contact',
    'footer.social': 'Réseaux sociaux',
    'footer.quote': '"L\'innovation distingue un leader d\'un suiveur." - Steve Jobs',
    'footer.rights': 'Tous droits réservés',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.experience': 'Experience',
    'nav.projects': 'Projects',
    'nav.education': 'Education',
    'nav.contact': 'Contact',
    
    // Hero
    'hero.name': 'Ghada Turki',
    'hero.title': 'Engineering Student in Electromechanics – 5th year at ESPRIT',
    'hero.master': 'Holder of a Professional Master\'s in Mechatronics',
    'hero.tagline': 'I transform ideas into prototypes… and industrial problems into intelligent solutions',
    'hero.viewProjects': 'View my projects',
    'hero.downloadCV': 'Download my CV',
    
    // About
    'about.title': 'About',
    'about.subtitle': 'Engineer Profile',
    'about.professionalProfile': 'Professional profile',
    'about.description': 'Holder of a Professional Master\'s in Mechatronics and Electromechanical Engineering student, with expertise in mechanical design, automation and software development. Passionate about innovation and automated systems, I seek to apply my skills in a dynamic environment through an end-of-study internship.',
    'about.objective': 'My goal is to contribute to the digital transformation of industry by developing intelligent solutions that combine mechanics, electronics and artificial intelligence.',
    'about.keyDomains': 'Key domains',
    'about.industrialAutomation': 'Industrial automation',
    'about.industrialAutomationDesc': 'Design and development of automated systems for Industry 4.0',
    'about.robotics': 'Robotics',
    'about.roboticsDesc': 'Development of autonomous robots and intelligent robotic systems',
    'about.iot': 'IoT & Embedded systems',
    'about.iotDesc': 'Integration of sensors, microcontrollers and communication protocols',
    'about.ar': 'Augmented reality',
    'about.arDesc': 'AR applications for training and industrial maintenance',
    'about.softSkills': 'Soft Skills',
    'about.innovation': 'Innovation',
    'about.teamwork': 'Teamwork',
    'about.autonomy': 'Autonomy',
    'about.analytical': 'Analytical mind',
    'about.problemSolving': 'Problem solving',
    'about.leadership': 'Leadership',
    
    // Experience
    'experience.title': 'Experience',
    'experience.subtitle': 'Professional journey',
    'experience.matech2025.position': 'End-of-study thesis',
    'experience.matech2025.description': 'Design and development of a generator emulator and its augmented reality mobile application',
    'experience.gd2025.position': 'Engineering internship',
    'experience.gd2025.description': 'Development of an innovative production supervision solution with Python desktop application and automated counting system',
    'experience.matech2023.position': 'End-of-study internship',
    'experience.matech2023.description': 'Design and development of a generator fault simulator and Java mobile application',
    'experience.csm2022.position': 'Technician internship',
    'experience.csm2022.description': 'Improvement of the Trepko Seau machine - Design of a machine for placing containers on the conveyor',
    'experience.wewire2021.position': 'Initiation internship',
    'experience.wewire2021.description': 'Discovery of company activities, learning cable manufacturing and application of Lean principles',
    
    // Projects
    'projects.title': 'Projects',
    'projects.subtitle': 'Discover my engineering achievements, from robotics to artificial intelligence',
    'projects.viewDetails': 'View details',
    'projects.description': 'Description',
    'projects.problem': 'Problem',
    'projects.solution': 'Solution',
    'projects.technologies': 'Technologies used',
    'projects.close': 'Close',
    'projects.project1.title': 'Autonomous crack detection robot',
    'projects.project1.description': 'Intelligent robot using AI to automatically detect cracks in structures',
    'projects.project1.problem': 'Manual crack detection is costly and error-prone in industrial inspections',
    'projects.project1.solution': 'Development of an autonomous robot equipped with cameras and AI algorithms for automatic detection',
    'projects.project1.detail': 'Crack detection robot implemented using VGG16, which is a deep convolutional neural network (CNN) model specialized in image classification. The system uses an ESP32 board for robot control and real-time processing of images captured by the camera. The VGG16 model, pre-trained on ImageNet, was fine-tuned to detect and classify cracks in structures, enabling automated and precise inspection.',
    'projects.project2.title': 'Generator emulator + AR',
    'projects.project2.description': 'Mobile augmented reality application to virtually explore the components of a generator',
    'projects.project2.problem': 'Complex and costly technical training for technicians on generators',
    'projects.project2.solution': 'Immersive AR application with integrated quiz enabling interactive learning of components',
    'projects.project7.title': 'Generator fault simulator',
    'projects.project7.description': 'Design and development of a generator fault simulator with mobile application',
    'projects.project7.problem': 'Training technicians on generator faults requires expensive and complex real equipment',
    'projects.project7.solution': 'Development of a fault simulator with Guardrevolution controller and Java mobile application for learning',
    'projects.project3.title': 'Automated cable counting system',
    'projects.project3.description': 'Automated cable counting system in industrial environment, integrating an electronic, software and mechanical solution',
    'projects.project3.problem': 'Manual counting of produced cables is time-consuming, prone to human errors and unreliable for real-time production monitoring',
    'projects.project3.solution': 'Development of an automated counting station based on a proximity sensor, an Arduino board and serial communication for data transmission',
    'projects.project3.detail': 'Automated cable counting system in industrial environment, integrating an electronic, software and mechanical solution to improve production supervision and manufacturing data reliability.',
    'projects.project3.features': 'Main features',
    'projects.project3.feature1': 'Automatic detection of cable passage',
    'projects.project3.feature2': 'Reliable and accurate real-time counting',
    'projects.project3.feature3': 'Data transmission to a supervision application',
    'projects.project3.feature4': 'Easy integration into an existing production line',
    'projects.project3.electronic': 'Electronic design',
    'projects.project3.electronic1': 'Replacement of the initial board with an Arduino board',
    'projects.project3.electronic2': 'Integration of an E3F-DS30C4 proximity sensor',
    'projects.project3.electronic3': 'Complete wiring diagram implementation',
    'projects.project3.electronic4': 'Reliability testing under industrial conditions',
    'projects.project3.programming': 'Programming',
    'projects.project3.programming1': 'Programming under Arduino IDE',
    'projects.project3.programming2': 'Implementation of a falling edge detection algorithm to ensure accurate counting and avoid duplicates',
    'projects.project3.programming3': 'Automatic counter increment',
    'projects.project3.programming4': 'Serial communication for data display and processing',
    'projects.project3.mechanical': 'Mechanical design & Implementation',
    'projects.project3.mechanical1': 'Complete workstation design under SolidWorks',
    'projects.project3.mechanical2': 'Complete system assembly (Arduino + sensor + mechanical structure)',
    'projects.project3.mechanical3': 'Validation of proper automatic counting operation',
    'projects.project8.title': 'Intelligent desktop application for production management and monitoring',
    'projects.project8.description': 'Intelligent desktop application dedicated to industrial production management and monitoring, enabling replacement of a manual system based on paper forms with an automated digital solution',
    'projects.project8.problem': 'Monitoring relied on manually filled paper forms, physical counting via numbered belts and a posteriori calculation. This system was time-consuming, prone to human errors and poorly suited for real-time monitoring',
    'projects.project8.solution': 'Development of a complete desktop application integrating worker management, shift monitoring, data collection and analysis, with facial recognition and QR codes',
    'projects.project9.title': 'Mobile application for interpreting generator error codes',
    'projects.project9.description': 'Simple mobile application allowing technicians to enter an error code displayed on the Guard Revolution AMF25 controller and instantly display the detailed description of the fault',
    'projects.project9.problem': 'Error codes displayed on the controller are technical and unclear, difficult to interpret without documentation, causing time loss for technicians during interventions',
    'projects.project9.solution': 'Development of a lightweight and intuitive mobile application enabling manual entry of the error code and instant display of its detailed meaning',
    'projects.project4.title': 'Line follower & obstacle detector',
    'projects.project4.description': 'Autonomous robot capable of following a line and intelligently avoiding obstacles',
    'projects.project4.problem': 'Need for autonomous robots for navigation in structured environments',
    'projects.project4.solution': 'Development of a robot with line following algorithms and obstacle detection',
    'projects.project5.title': 'Robotic arm drawing on wood (Woodcraft)',
    'projects.project5.description': 'Precise control of a robotic arm to create complex patterns on wood',
    'projects.project5.problem': 'Manual creation of complex patterns on wood is long and imprecise',
    'projects.project5.solution': 'Programming of a robotic arm with precise trajectories for artistic machining',
    'projects.project5.objective': 'Project Objective',
    'projects.project5.objectiveDesc': 'The goal of our project is to create a woodcraft, where a robot will be able to write a word or draw on wood in an artisanal manner. In our case, the robot will be tasked with writing the word "meca" on a wooden surface.',
    'projects.project5.step1': 'Design on SolidWorks',
    'projects.project5.step1Desc': 'The first step consists of designing the work table, the robot location and the piece on which it will write the word "meca". This detailed design was carried out using SolidWorks software.',
    'projects.project5.step2': 'Programming with RT Tool Box - Hand Creation',
    'projects.project5.step2Desc': 'We used RT Tool Box software to program the robot. Initially, we created our hand, thus defining the configuration of tools and end effectors that the robot will use for writing on wood.',
    'projects.project5.step3': 'Part Integration into RT Tool Box',
    'projects.project5.step3Desc': 'Following the creation of the hand, we integrated the parts previously designed in SolidWorks into RT Tool Box software. This step ensures synchronization between mechanical elements and programming, ensuring consistent execution of robot movements.',
    'projects.project5.step4': 'Advanced Programming with Robot Teaching Method',
    'projects.project5.step4Desc': 'Finally, through the robot teaching method, we refined the robot programming. This interactive approach allowed the robot to learn and dynamically adapt to the wood surface, thus improving its ability to write the word "meca" with precision and efficiency.',
    'projects.project5.highlights': 'Project highlights',
    'projects.project5.highlight1': 'Complete integration: From 3D design (SolidWorks) to robotic programming (RT Tool Box)',
    'projects.project5.highlight2': 'Artisanal precision: Creation of complex patterns with high precision',
    'projects.project5.highlight3': 'Teaching method: Dynamic adaptation of the robot to the wood surface',
    'projects.project5.highlight4': 'Automation: Reduction of production time and improvement of reproducibility',
    'projects.project5.highlight5': 'Industrial application: Solution applicable to wood product personalization',
    'projects.project6.title': 'Smart tank with Node-RED',
    'projects.project6.description': 'Intelligent tank monitoring system with real-time dashboard and alerts',
    'projects.project6.problem': 'Manual tank monitoring is inefficient and risks overflow or shortage',
    'projects.project6.solution': 'Node-RED dashboard with MQTT and ESP32 for real-time monitoring and automatic alerts',
    'projects.project10.title': 'Industrial supervision application & maintenance indicators',
    'projects.project10.description': 'Industrial supervision application enabling acquisition, recording and analysis of machine stops, production data and process parameters, with automatic calculation of MTTR and MTBF maintenance indicators',
    'projects.project10.problem': 'In an industrial environment, the absence of a structured supervision system leads to poor traceability of machine stops, limited monitoring of production and material consumption, and difficulty in analyzing performance and maintenance',
    'projects.project10.solution': 'Development of a centralized supervision application integrating stop signal acquisition via an acquisition board, process data recording in a database, and a multi-window graphical interface for monitoring, analysis and decision-making',
    'projects.project10.value': 'Project added value',
    'projects.project10.value1': 'Complete vision acquisition → supervision → analysis',
    'projects.project10.value2': 'Industrial maintenance skills',
    'projects.project10.value3': 'Data exploitation for decision support',
    'projects.project10.value4': 'WinDev and Proteus 8 integration',
    'projects.project10.detail': 'Industrial supervision application enabling acquisition, recording and analysis of machine stops, production data and process parameters, with automatic calculation of MTTR and MTBF maintenance indicators, developed under WinDev.',
    'projects.project10.problematic': 'Problem',
    'projects.project10.problematicDesc': 'In an industrial environment, the absence of a structured supervision system leads to:',
    'projects.project10.problematic1': 'poor traceability of machine stops',
    'projects.project10.problematic2': 'limited monitoring of production and material consumption',
    'projects.project10.problematic3': 'difficulty in analyzing performance and maintenance',
    'projects.project10.solutionTitle': 'Solution',
    'projects.project10.solutionDesc': 'Development of a centralized supervision application integrating:',
    'projects.project10.solution1': 'stop signal acquisition via an acquisition board',
    'projects.project10.solution2': 'process data recording in a database',
    'projects.project10.solution3': 'multi-window graphical interface for monitoring, analysis and decision-making',
    'projects.project10.acquisition': 'Machine stop acquisition',
    'projects.project10.acquisition1': 'Pin 11: Power fault stop',
    'projects.project10.acquisition2': 'Pin 10: Pressure fault stop',
    'projects.project10.acquisition3': 'Pin 9: Operator stop',
    'projects.project10.acquisitionDesc': 'Each stop is recorded with: stop type, date and time, consultable history',
    'projects.project10.interface': 'Graphical interface (WinDev)',
    'projects.project10.window1': 'Window 1 – Stops & Maintenance',
    'projects.project10.window1Desc': 'List of stops with type, date, time. Filtering by type and period. Calculation and display of indicators: MTTR (Mean Time To Repair) and MTBF (Mean Time Between Failures)',
    'projects.project10.window2': 'Window 2 – Production monitoring',
    'projects.project10.window2Desc': 'Display of daily production: conforming parts, non-conforming parts, total production. Quick analysis of production performance',
    'projects.project10.window3': 'Window 3 – Process monitoring',
    'projects.project10.window3Desc': 'Monitoring of raw material consumption as a function of time (per day). Temperature history. Detection and recording of threshold exceedances (temperature > 70 °C). Data filtering by date',
    'projects.project10.windowMain': 'Main window',
    'projects.project10.windowMainDesc': 'Central menu allowing access to different windows. Simple and intuitive navigation',
    'projects.project10.development': 'Development & Programming',
    'projects.project10.dev1': 'Acquisition board programming',
    'projects.project10.dev2': 'Acquisition and recording: machine stops, production data, temperature data, raw material consumption',
    'projects.project10.dev3': 'Development of graphical interface and database under WinDev',
    'projects.project10.dev4': 'Implementation of filters and statistical calculations',
    
    // Education
    'education.title': 'Education',
    'education.subtitle': 'Academic journey',
    'education.esprit.degree': 'Engineering cycle in Electromechanics – Mechatronics specialization',
    'education.esprit.institution': 'Private Higher School of Engineering and Technologies - ESPRIT',
    'education.esprit.period': '2024 - Present',
    'education.esprit.status': 'In progress',
    'education.esprit.description': 'In-depth training in mechatronics, automation and intelligent systems',
    'education.istic.degree': 'Co-constructed Professional Master\'s in Mechatronics',
    'education.istic.institution': 'Higher Institute of Information and Communication Technologies - ISTIC',
    'education.istic.period': '2023 - 2025',
    'education.istic.status': 'Graduated',
    'education.istic.description': 'Specialization in mechatronic systems and mechanical-electronic-informatics integration',
    'education.isetn.degree': 'Applied degree in mechanical engineering',
    'education.isetn.institution': 'Higher Institute of Technological Studies of Nabeul - ISETN',
    'education.isetn.period': '2020 - 2023',
    'education.isetn.status': 'Graduated',
    'education.isetn.description': 'Foundations in mechanical engineering, design and manufacturing',
    'education.certifications': 'Certifications',
    'education.associative': 'Associative life',
    'education.associative.member': 'Member of the Environmental Education Association of Hammamet',
    'education.associative.memberDesc': 'Participation in several projects and training sessions.',
    'education.aiesec.title': 'AIESEC – Volunteer internship in Turkey, Izmit (06/2023 - 08/2023)',
    'education.aiesec.description': 'International collaboration to organize community events, animation of "Talk to Practice" sessions in English and direction of educational activities for children and adults. Certification obtained in Leadership Development Experience as part of the Global Volunteer project "Youth 4 Impact" targeting Sustainable Development Goal #4 (Quality Education).',
    'education.aiesec.download': 'Download Leadership Development Experience certificate',
    'education.bal.title': 'Projects Ball 2025 – ESPRIT',
    'education.bal.description': 'As part of the Projects Ball 2025 organized by ESPRIT, I had the opportunity to collaborate with a team of 6 people on an automatic crack detection project. This experience allowed me to strengthen my teamwork and technical problem-solving skills.',
    'education.bal.download': 'Download participation certificate',
    'education.download': 'Download',
    
    // Contact
    'contact.title': 'Contact',
    'contact.subtitle': 'Interested in my profile? Feel free to contact me to discuss your projects',
    'contact.info': 'Contact information',
    'contact.infoDesc': 'I am available to discuss projects, internships or collaboration opportunities in the field of engineering and technological innovation.',
    'contact.email': 'Email',
    'contact.phone': 'Phone',
    'contact.location': 'Location',
    'contact.social': 'Social networks',
    'contact.fullName': 'Full name',
    'contact.namePlaceholder': 'Your name',
    'contact.emailPlaceholder': 'your.email@example.com',
    'contact.subject': 'Subject',
    'contact.subjectPlaceholder': 'Subject of your message',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Your message...',
    'contact.send': 'Send message',
    'contact.sent': 'Message sent!',
    
    // Footer
    'footer.tagline': 'Transforming mechanics into intelligent systems',
    'footer.quickLinks': 'Quick links',
    'footer.about': 'About',
    'footer.projects': 'Projects',
    'footer.contact': 'Contact',
    'footer.social': 'Social networks',
    'footer.quote': '"Innovation distinguishes a leader from a follower." - Steve Jobs',
    'footer.rights': 'All rights reserved',
  },
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('fr')

  useEffect(() => {
    // Récupérer la langue sauvegardée
    const saved = localStorage.getItem('language') as Language
    if (saved && (saved === 'fr' || saved === 'en')) {
      setLanguageState(saved)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('language', lang)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.fr] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}
